### ISSUE TITLE
Version 1.8.8 Can't start http server with default args

### ISSUE THREAD

**Issue by crazyofapple** [hanxiao/bert-as-service#303]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [x] Are you running the latest `bert-as-service`?
* [x] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [x] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [x] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**System information**

> Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- `bert-as-service` version: 
- GPU model and memory:
- CPU model and memory:
---

### Description

Using a default args in README, the http server is failed. I degrade to v1.8.2, the problem is solved.

bert-serving-start -model_dir=/MY_MODEL -http_port 8125
curl -X POST http://0.0.0.0:8125/encode 
-H 'content-type: application/json' 
-d '{"id": 123,"texts": ["hello world"], "is_tokenized": false}'

with lsof -i :8125, it's nothing.

...

**Comment by hanxiao** [comment]
1.8.8 should work see #296

**Comment by GrgrLmml** [comment]
same problem here even with 1.8.8

➜  query-embedding curl -X POST http://127.0.0.1:8125/encode \
  -H 'content-type: application/json' \
  -d '{"id": 123,"texts": ["hello world"], "is_tokenized": false}'
curl: (7) Failed to connect to 127.0.0.1 port 8125: Connection refused

here is my setup:

(query-embedding) ➜  query-embedding pip freeze
absl-py==0.7.1
astor==0.7.1
bert-serving-client==1.8.8
bert-serving-server==1.8.8
Click==7.0
Flask==1.0.2
Flask-Compress==1.4.0
Flask-Cors==3.0.7
Flask-JSON==0.3.3
gast==0.2.2
GPUtil==1.4.0
grpcio==1.19.0
h5py==2.9.0
itsdangerous==1.1.0
Jinja2==2.10
Keras-Applications==1.0.7
Keras-Preprocessing==1.0.9
Markdown==3.1
MarkupSafe==1.1.1
mock==2.0.0
numpy==1.16.2
pbr==5.1.3
protobuf==3.7.1
pyzmq==18.0.1
six==1.12.0
tensorboard==1.13.1
tensorflow==1.13.1
tensorflow-estimator==1.13.0
termcolor==1.1.0
Werkzeug==0.15.1
You are using pip version 10.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

(query-embedding) ➜  query-embedding bert-serving-start -model_dir \`pwd\`/uncased_L-12_H-768_A-12/ -num_worker=2 -http_port 8125
usage: /Users/gla/py/annotateimages/query-embedding/bin/bert-serving-start -model_dir /Users/gla/git/query-embedding/uncased_L-12_H-768_A-12/ -num_worker=2 -http_port 8125
                 ARG   VALUE
__________________________________________________
           ckpt_name = bert_model.ckpt
         config_name = bert_config.json
                cors = *
                 cpu = False
          device_map = []
  fixed_embed_length = False
                fp16 = False
 gpu_memory_fraction = 0.5
       graph_tmp_dir = None
    http_max_connect = 10
           http_port = 8125
        mask_cls_sep = False
      max_batch_size = 256
         max_seq_len = 25
           model_dir = /Users/gla/git/query-embedding/uncased_L-12_H-768_A-12/
          num_worker = 2
       pooling_layer = [-2]
    pooling_strategy = REDUCE_MEAN
                port = 5555
            port_out = 5556
       prefetch_size = 10
 priority_batch_size = 16
show_tokens_to_client = False
     tuned_model_dir = None
             verbose = False
                 xla = False

I:VENTILATOR:[__i:__i: 66]:freeze, optimize and export graph, could take a while...
I:GRAPHOPT:[gra:opt: 52]:model config: /Users/gla/git/query-embedding/uncased_L-12_H-768_A-12/bert_config.json
I:GRAPHOPT:[gra:opt: 55]:checkpoint: /Users/gla/git/query-embedding/uncased_L-12_H-768_A-12/bert_model.ckpt
I:GRAPHOPT:[gra:opt: 59]:build graph...

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

I:GRAPHOPT:[gra:opt:128]:load parameters from checkpoint...
I:GRAPHOPT:[gra:opt:132]:optimize...
I:GRAPHOPT:[gra:opt:140]:freeze...
I:GRAPHOPT:[gra:opt:145]:write graph to a tmp file: /var/folders/fp/zb8y8hzn371dwkp2xtgs_8w9tvxd3s/T/tmpdwmqwkgk
I:VENTILATOR:[__i:__i: 74]:optimized graph is stored at: /var/folders/fp/zb8y8hzn371dwkp2xtgs_8w9tvxd3s/T/tmpdwmqwkgk
I:VENTILATOR:[__i:_ru:128]:bind all sockets
I:VENTILATOR:[__i:_ru:132]:open 8 ventilator-worker sockets
I:VENTILATOR:[__i:_ru:135]:start the sink
I:SINK:[__i:_ru:303]:ready
I:VENTILATOR:[__i:_ge:219]:get devices
W:VENTILATOR:[__i:_ge:243]:no GPU available, fall back to CPU
I:VENTILATOR:[__i:_ge:252]:device map: 
		worker  0 -> cpu
		worker  1 -> cpu
I:VENTILATOR:[__i:_ru:151]:start http proxy
I:WORKER-0:[__i:_ru:514]:use device cpu, load graph from /var/folders/fp/zb8y8hzn371dwkp2xtgs_8w9tvxd3s/T/tmpdwmqwkgk
I:WORKER-1:[__i:_ru:514]:use device cpu, load graph from /var/folders/fp/zb8y8hzn371dwkp2xtgs_8w9tvxd3s/T/tmpdwmqwkgk
I:WORKER-0:[__i:gen:542]:ready and listening!
I:WORKER-1:[__i:gen:542]:ready and listening!

**Comment by hanxiao** [comment]
I confirm it's a bug, related to #296 fixing it now

**Comment by hanxiao** [comment]
fyi, this issue is fixed in #305 and the new feature is available since 1.8.9, please do
```
pip install -U bert-serving-server bert-serving-client
```
for the update.

When you start the server with -http_port, you should see something like this
![image](https://user-images.githubusercontent.com/2041322/55401775-5749a900-5584-11e9-82b3-ee0a924bbf59.png)

```
I:VENTILATOR:[__i:_ru:163]:all set, ready to serve request!
```
this means the server is ready.

**Comment by bigrig2212** [comment]
Same issue here via docker setup. Using: 
bert-serving-server==1.8.9
bert-serving-client==1.8.9
(I did get it working from a non-docker install).

Weird thing is that everything looks good. Health check is running... just can't see the http port.
 
<img width="827" alt="Screen Shot 2020-05-12 at 4 03 17 PM" src="https://user-images.githubusercontent.com/19869387/81754095-2667c300-946a-11ea-928e-ba580be4c2bc.png">

<img width="504" alt="Screen Shot 2020-05-12 at 4 04 10 PM" src="https://user-images.githubusercontent.com/19869387/81754128-3da6b080-946a-11ea-8912-21bf22b72a89.png">

**Comment by bigrig2212** [comment]
ooo, i just got the flask message. but still, port is not found...

<img width="651" alt="Screen Shot 2020-05-12 at 5 05 09 PM" src="https://user-images.githubusercontent.com/19869387/81757214-fe309200-9472-11ea-9f32-2063131ba612.png">

**Comment by bigrig2212** [comment]
Of course, after many hours of trying I got it working right after posting with:
docker run -p 8000:8125 MYID

**Comment by NicoleJaneway** [comment]
Running into a similar issue trying docker compose.  I tried setting 8000:8125, but no dice - still seeing 'Connection refused'.  Any thoughts? @bigrig2212 @hanxiao
