### ISSUE TITLE
zmq.error.ZMQError: Address already in use

### ISSUE THREAD

**Issue by calliwen** [hanxiao/bert-as-service#84]
/home/inplus-dm/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
usage: app.py -model_dir ./BERT_BASE_DIR/english_L-12_H-768_A-12/ -num_worker=4
                 ARG   VALUE__________________________________________________
 gpu_memory_fraction = 0.5      max_batch_size = 256         max_seq_len = 25
           model_dir = ./BERT_BASE_DIR/english_L-12_H-768_A-12/
          num_worker = 4
       pooling_layer = [-2]
    pooling_strategy = REDUCE_MEAN
                port = 5555
            port_out = 5556

Traceback (most recent call last):
  File "app.py", line 44, in <module>
    server = BertServer(args)
  File "/home/inplus-dm/gaoy/bert-as-service/service/server.py", line 62, in __init__
    self.frontend.bind('tcp://*:%d' % self.port)
  File "zmq/backend/cython/socket.pyx", line 547, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython. checkrc._check_rc
zmq.error.ZMQError: Address already in use
-------------------------spliting line------------------------------
I'm newer for ZMQ, when I operated on the steps, I got this exception. It's not working even though retrying.

**Comment by calliwen** [comment]
I restart the server through checking running python processes and kill it.
ps ax | grep python # this command will list the python process backend.
kill -9 pid # choose the running processes to kill

**Comment by hanxiao** [comment]
so is it solved?

**Comment by calliwen** [comment]
> so is it solved?


In my case, the problem is solved.
Thanks.

**Comment by wwwwwwwwwwjj** [comment]
I also have same problem, how to solve it?

**Comment by rcmcabral** [comment]
Just adding a possible solution to help other people. I was able to solve this problem by assigning a different port number to the server.

`start-bert-as-service.py -model_dir
 uncased_L-12_H-768_A-12 -num_worker=1 -cpu -max_batch_size 16 -port 8190`

Hope it helps.

**Comment by jy2k** [comment]
The error is still persisting for me:
I:VENTILATOR:[__i:_ru:136]:start the sink
Process BertSink-2:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Users/yarkoni/Projects/Teva/bert1/venv/lib/python3.7/site-packages/bert_serving/server/__init__.py", line 282, in run
    self._run()
  File "/Users/yarkoni/Projects/Teva/bert1/venv/lib/python3.7/site-packages/zmq/decorators.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/Users/yarkoni/Projects/Teva/bert1/venv/lib/python3.7/site-packages/zmq/decorators.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/Users/yarkoni/Projects/Teva/bert1/venv/lib/python3.7/site-packages/zmq/decorators.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/Users/yarkoni/Projects/Teva/bert1/venv/lib/python3.7/site-packages/bert_serving/server/__init__.py", line 290, in _run
    sender.bind('tcp://*:%d' % self.port)
  File "zmq/backend/cython/socket.pyx", line 550, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 26, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use

**Comment by danyang-liu** [comment]
> Just adding a possible solution to help other people. I was able to solve this problem by assigning a different port number to the server.
> 
> `start-bert-as-service.py -model_dir uncased_L-12_H-768_A-12 -num_worker=1 -cpu -max_batch_size 16 -port 8190`
> 
> Hope it helps.

it works for me.
